#!/usr/bin/env node

var log = require("leg")(process.stdout),
    Tremor = require("tremor"),
    package = require("./package.json"),
    request = require("request");

if (process.argv.length !== 4) {
  console.warn("Usage: tremor-elastic <elasticsearch url> <glob>");
  process.exit(1);
}

var elasticSearch = process.argv[2],
    glob = process.argv[3];

var tremor = new Tremor({glob: glob});

tremor.on("following", function(o) {
  log.info("following file", {name: o.name, file: o.file});
});

tremor.on("data", function(o) {
  request({method: "POST", uri: elasticSearch, json: o}, function(err, res, data) {
    if (err) {
      return log.warn("couldn't submit entry", {err: err, input: o});
    }

    if (res.statusCode !== 201) {
      return log.warn("invalid response from elasticsearch", {code: res.statusCode, input: o, data: data});
    }
  });
});

log.info("successfully started", {
  package: {
    name: package.name,
    version: package.version,
  },
  config: {
    elasticSearch: elasticSearch,
    glob: glob,
  },
});
